### PR TITLE
Update v2 API calls to 2.2

### PR DESCRIPTION
**Pull request by raelik**
Facebook has deprecated API versions before v2.2.  Updated the gem version as well to ensure anyone still using this gem gets this update.

### CODE REVIEW

**Comment by jdejong** [comment]
Please merge this as soon as possible. We had to go to a forked version to keep production up and running for our application.

**Comment by nov** [comment]
can you try `fb_graph2` gem?

**Comment by jdejong** [comment]
It currently doesn't have any of the Ad or Marketing API's as far as I can tell. I know Facebook's release schedule is going to be different for the Graph API and the Marketing API now, and it may make sense to split the functionality into a separate gem at this point but I didn't know what your plan was. If your going to try and bring it into fb_graph2 then we can help with some of that since we use most of the marketing API ourselves. Otherwise we will create a separate gem for the marketing api.

Thoughts?

Jonathan De Jong
Partner
[Description: Description: cid:image001.jpg@01C8B1D4.FB23A720]
jdejong@sparknettech.com<mailto:jdejong@sparknettech.com>
http://www.sparknettech.com<http://www.sparknettech.com/>
999 Old Eagle School Road * Suite 121 * Wayne, PA * 19087
800.893.2650<tel:800.893.2650>.p * 610.329.9510<tel:610.329.9510>.c * 800.893.6075<tel:800.893.6075>.f

**Comment by nov** [comment]
To be honest, I don't know well about Ads APIs.
All code around Ads APIs are from contributors...

**Comment by nov** [comment]
BTW, v2.0 isn't deprecated yet.
https://developers.facebook.com/docs/apps/changelog

**Comment by jdejong** [comment]
It is for Marketing API. They only give you 90 days after they publish a release now on that API.

Jonathan De Jong
Partner
[Description: Description: cid:image001.jpg@01C8B1D4.FB23A720]
jdejong@sparknettech.com<mailto:jdejong@sparknettech.com>
http://www.sparknettech.com<http://www.sparknettech.com/>
999 Old Eagle School Road * Suite 121 * Wayne, PA * 19087
800.893.2650<tel:800.893.2650>.p * 610.329.9510<tel:610.329.9510>.c * 800.893.6075<tel:800.893.6075>.f

**Comment by nov** [comment]
Then probably what you need is something like this.
https://github.com/nov/fb_graph/commit/e2dc6370f6b3d5fe3b13e048b142295cbd38dc6a

I can't guarantee this gem works fine with v2.2 or later though..
If this is OK for you, I'll release new version.

**Comment by jdejong** [comment]
I ended up forking and changed the /lib/fb_graph.rb and we have been running on that.

https://github.com/jdejong/fb_graph/blob/master/lib/fb_graph.rb

The bigger thing is there are a bunch of new Marketing API's which we have created as local model's in our App that ideally we are going to put into a Gem. If your ok with it we can start working on adding it to fb_graph2, otherwise we will create a separate gem for the marketing api only.

Jonathan De Jong
Partner
[Description: Description: cid:image001.jpg@01C8B1D4.FB23A720]
jdejong@sparknettech.com<mailto:jdejong@sparknettech.com>
http://www.sparknettech.com<http://www.sparknettech.com/>
999 Old Eagle School Road * Suite 121 * Wayne, PA * 19087
800.893.2650<tel:800.893.2650>.p * 610.329.9510<tel:610.329.9510>.c * 800.893.6075<tel:800.893.6075>.f

**Comment by nov** [comment]
OK, then I close this issue.
I think it's better to have a separate gem for Ads API.

**Pull request closed without merging**
